Translation beginnings
Nv7-GitHub/Nv7Haven pull request #131
Opened 2023-01-06 01:32 UTC by abnormalhare

This will allow you to set a personal language (hopefully) and have the bot translate messages in the future.

2023-01-06 03:24 UTC, Nv7-GitHub requested changes
The use of reflection disgusts me.
Some pretty major issues + not thread safe, but promising?

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/translations/translations.go
> +			AutoComplete(t.AutoComplete),
Don't use AutoComplete, use the Choices instead -- This makes discord validate the language and doesn't require it to load

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +		translations: translations{
Change this to use named fields

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +	lang := `SELECT FROM config WHERE "user"=$2`
This isn't actually running a query, it is just defining a string to the query's code

Even if this did run the query, this would cause a major performance hit since it would have to run a ~100ms query like 20 times per command usage

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +		if LanguageTable[i].name == lang {
Use a HashMap here, this also needs to be wrapped with a `*sync.RWMutex`.RLock

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +		fmt.Println(err)
Use `log.Println("translation error", err)` and return the English translation

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +func getAttr(obj interface{}, fieldName string) reflect.Value {
This is horrible Go coding, REMOVE THIS
Very bad for performance, it violates type safety, and reflect is generally avoided as much as possible (especially in this scenario)

2023-01-06 03:24 UTC, Nv7-GitHub commented on eod/types/translations.go
> +func Translate(phrase string, var1 interface{}, var2 interface{}, var3 interface{}) string {
How do you pass more than 3 values? Accept `map[string]any` instead and get rid of the `Variables` struct, or create type definitions for every message and accept `any`

2023-01-06 13:43 UTC, abnormalhare commented on eod/types/translations.go
> +		if LanguageTable[i].name == lang {
Idk if i did it right, but im guessing i did it, so

2023-01-06 16:11 UTC, Nv7-GitHub requested changes
You forgot to fix some bugs I mentioned last time, some new bugs introduced. Make sure to use HashMap instead of a struct if you want to index it.

2023-01-06 16:11 UTC, Nv7-GitHub commented on eod/types/translations.go
> +	nameMayNotContain    string
Capitalize all the fields (but you probably want hashmap?)

2023-01-06 16:11 UTC, Nv7-GitHub commented on eod/types/translations.go
> +type Variables struct {
Don't use this struct, use `map[string]any` instead
Perhaps do
```go
type Variables map[string]any
```
if you want nice syntax

2023-01-06 16:11 UTC, Nv7-GitHub commented on eod/translations/translate.go
> +func Translate(phrase string, var1 interface{}, var2 interface{}, var3 interface{}) string {
Accept a `map[string]any` instead of var1, and use the `any` type instead of `interface{}`. Also, add `(t *Translations)` so it can access the DB

2023-01-06 16:11 UTC, Nv7-GitHub commented on eod/translations/translate.go
> +	index := LanguageTable[lang][phrase]
I don't think you can index structs like this... Does this compile?

2023-01-27 08:48 UTC, rayzchen commented
Wait translations weren't supported?

2023-01-27 16:07 UTC, Nv7-GitHub commented
No, they were pretty broken in the old bot and none of the translators were committed enough

2023-01-27 16:12 UTC, rayzchen commented
I mean I would be committed enough
Where is the schema for the json though and how do I use it

2023-01-27 16:53 UTC, Nv7-GitHub commented
It's not in the re-write and I don't plan to add it, it's a huge pain to develop for and only makes sense in a finished product

2024-06-10 00:40 UTC, closed without merging