Add text commands for lb and inv
Nv7-GitHub/Nv7Haven pull request #134
Opened 2023-01-19 22:18 UTC by rayzchen

!inv also checks user id or ping

2023-01-19 22:45 UTC, Nv7-GitHub commented
Use the discord TODO Forum instead of github for EoDE-related things

2023-01-19 22:46 UTC, Nv7-GitHub commented on eod/msgs.go
> +			b.pages.Inv(c, []any{any(content[2:len(content)-1]), nil})
Make sure to check that all of these indexes are in bounds, text commands often cause crashes because of mistakes like this

2023-01-19 22:49 UTC, Nv7-GitHub commented on eod/msgs.go
> +		b.pages.Lb(c, []any{nil, nil, nil})
Why are there 3 parameters when inv only accepts 2 values...?

2023-01-19 22:51 UTC, Nv7-GitHub requested changes
Seems like this would cause a lot of crashes
Probably don't change slash command code for text commands

2023-01-19 22:51 UTC, Nv7-GitHub commented on eod/pages/inv.go
> +		if dguser, ok := args[0].(*discordgo.User); ok {
Instead of doing this fetch the `discordgo.User` object and pass it in

2023-01-20 07:44 UTC, rayzchen commented on eod/msgs.go
> +			b.pages.Inv(c, []any{any(content[2:len(content)-1]), nil})
well surely if it starts with <@ and ends with > its gotta be at least 3 long right
worst case is when the bounds return an empty string

2023-01-20 07:45 UTC, rayzchen commented on eod/pages/inv.go
> +		if dguser, ok := args[0].(*discordgo.User); ok {
wdym

2023-01-20 07:46 UTC, rayzchen commented on eod/pages/inv.go
> +		if dguser, ok := args[0].(*discordgo.User); ok {
oh as in do that stuff in msgs.go?

2023-01-20 16:09 UTC, Nv7-GitHub commented on eod/msgs.go
> +			b.pages.Inv(c, []any{any(content[2:len(content)-1]), nil})
When you do `!inv <@>` does it crash?

2023-01-25 16:43 UTC, rayzchen commented
@Nv7-GitHub bump

2023-01-25 19:46 UTC, Nv7-GitHub commented
I'll pull this and try running it whenever I have time

2023-02-05 17:33 UTC, rayzchen commented
bro must be hella busy

2023-02-18 19:43 UTC, rayzchen commented
btw i have tested it and it does work

2023-02-18 19:43 UTC, rayzchen commented
it literally uses the same functions that the slash commands use, just with a bit of basic parsing

2023-04-06 01:34 UTC, Nv7-GitHub approved these changes
Ok I will merge

2023-04-06 01:34 UTC, merged