Delete combos command
Nv7-GitHub/Nv7Haven pull request #137
Opened 2023-08-18 14:53 UTC by rayzchen

Deletes all combos except for the oldest combo. Recalculates tree size.

please dont wait 6 months this time smh

2023-08-21 02:35 UTC, Nv7-GitHub requested changes
Code is confusing me

2023-08-21 02:35 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +func (e *Elements) deleteComboCmd(c sevcord.Ctx, opts []any) {
Rename to "DeleteCombo" to fit within naming scheme

2023-08-21 02:35 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +	// Get tree size
Why is `// Get tree size` commented 3 times? Most of the time its above code that doesn't even get the tree size, make the comments more descriptive

2023-08-21 02:35 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +	var currtreesize int
Why do you get the current tree size? It doesn't seem to be used at all

2023-08-21 02:35 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +	// Check if need to update parents
This comment should be `// Get tree size and update parents`, and all the other comments should be changed

2023-08-21 02:35 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +	if !loop {
What is `loop` for? Its just always false so this will always run... Probably take the code out of this if statement and delete the loop variable

2023-08-21 07:48 UTC, rayzchen commented on eod/elements/deletecmd.go
> +func (e *Elements) deleteComboCmd(c sevcord.Ctx, opts []any) {
Capital D?

2023-08-21 07:48 UTC, rayzchen commented on eod/elements/deletecmd.go
> +func (e *Elements) deleteComboCmd(c sevcord.Ctx, opts []any) {
Also the other edit commands are named like this

2023-08-21 07:48 UTC, rayzchen commented on eod/elements/deletecmd.go
> +	var currtreesize int
Its used to compare below isnt it?

2023-08-21 07:49 UTC, rayzchen commented on eod/elements/deletecmd.go
> +	if !loop {
I'm guessing its for when the tree has a loop in it, and its scanned by the sql query above it, not sure how to get rid of it but its also in the tree recalc code in elemcreate.go

2023-08-21 07:50 UTC, rayzchen commented on eod/elements/deletecmd.go
> +	var currtreesize int
Ah, nevermind, since there is only one combo left I don't check to see if the tree size is lower.

2023-08-21 07:51 UTC, rayzchen commented on eod/elements/deletecmd.go
> +	if !loop {
It is assigned to with `.Scan(&treesize, &loop)`

2023-08-21 16:21 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +func (e *Elements) deleteComboCmd(c sevcord.Ctx, opts []any) {
https://github.com/Nv7-GitHub/Nv7Haven/blob/1d302e0ffad20e8e2c6d77480233b35c154b1700/eod/elements/editcmd.go#L54 I don't think so

2023-08-21 16:24 UTC, Nv7-GitHub commented on eod/elements/deletecmd.go
> +	if !loop {
Oh yeah, but there can't be a loop with only the oldest combo so you can change the query to
```sql
WITH RECURSIVE parents(els, id) AS (
		VALUES($2::integer[], 0)
	UNION
		(SELECT b.parents els, b.id id FROM elements b INNER JOIN parents p ON b.id=ANY(p.els) where guild=$1)
	) SELECT COUNT(*)  FROM parents WHERE id>0
```
and get rid of the if statement

2023-08-31 22:28 UTC, Nv7-GitHub approved these changes
Looks good!

2023-08-31 22:28 UTC, merged