color text command + !c for category
Nv7-GitHub/Nv7Haven pull request #149
Opened 2024-11-30 23:08 UTC by SkitsTheSkitty

i have no idea if this will work

2024-12-01 17:50 UTC, Nv7-GitHub requested changes

2024-12-01 17:50 UTC, Nv7-GitHub commented on eod/msgs.go
> +			c.Respond(sevcord.NewMessage("Invalid format! " + types.RedCircle))
Add error message with the format of the command here

2024-12-01 17:50 UTC, Nv7-GitHub commented on eod/msgs.go
> +		b.elements.ColorCmd(c, strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1]))
1. Needs to support elements, categories, and queries
2. Did you compile this? ColorCmd only accepts 2 parameters - Also, in the future compile all code before making a PR with it because I don't compile these myself before merging and that would bring the bot down

2024-12-01 21:33 UTC, SkitsTheSkitty commented on eod/msgs.go
> +		b.elements.ColorCmd(c, strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1]))
Bestie idk how to code that in 💔 Sign isn't compatible with e/c/q cases either (Also I barely code, idk what compiling even means)

2025-01-15 16:01 UTC, Nv7-GitHub commented
Can you update the error message to include the correct format of the command (like !image)? Otherwise it looks good!

2025-01-19 04:30 UTC, Nv7-GitHub approved these changes
Looks good

2025-01-19 04:30 UTC, merged