add vukky autocat
Nv7-GitHub/Nv7Haven pull request #27
Opened 2021-07-07 20:40 UTC by Vukky123

this is a very nice PR that should work as far as I know

2021-07-07 20:41 UTC, Nv7-GitHub commented on eod/categories.go
> +	"Vukkies":    func(s string) bool { return strings.HasPrefix(strings.ToLower(s), "vukky") || strings.HasSuffix(strings.ToLower(s), "vukky") },
Can't it just use `strings.Contains` instead?

2021-07-07 20:42 UTC, Vukky123 commented on eod/categories.go
> +	"Vukkies":    func(s string) bool { return strings.HasPrefix(strings.ToLower(s), "vukky") || strings.HasSuffix(strings.ToLower(s), "vukky") },
this is very true, thank you for reminding me

2021-07-07 20:48 UTC, Nv7-GitHub requested changes

2021-07-07 20:48 UTC, Nv7-GitHub commented on eod/categories.go
> +	"Fukkies":    func(s string) bool { return strings.Contains(strings.ToLower(s), "fukky") },
No swear words pls

2021-07-07 20:49 UTC, Vukky123 commented on eod/categories.go
> +	"Fukkies":    func(s string) bool { return strings.Contains(strings.ToLower(s), "fukky") },
alrighty, the fukky category was more of a joke @vtheskeleton did anyway

2021-07-07 20:51 UTC, Nv7-GitHub approved these changes

2021-07-07 20:51 UTC, Nv7-GitHub commented
Looks ok!

2021-07-07 20:51 UTC, merged

2021-07-08 07:36 UTC, vtheskeleton commented on eod/categories.go
> +	"Fukkies":    func(s string) bool { return strings.Contains(strings.ToLower(s), "fukky") },
> alrighty, the fukky category was more of a joke @vtheskeleton did anyway

you dare drag me into this