Add a character limit to creator marks
Nv7-GitHub/Nv7Haven pull request #31
Opened 2021-07-10 22:23 UTC by Sightnado

The character limit is 1000 which should make sure that creator marks don't cause any element info pages to go past the message character limit of 2000

2021-07-16 23:38 UTC, Nv7-GitHub requested changes

2021-07-16 23:38 UTC, Nv7-GitHub commented on eod/pollcmds.go
> +	if len(mark) >= 1500 {
The SQL DB has a limit of 2400, so this number (and the error message) should be 2400 I think

2021-07-17 23:43 UTC, Sightnado commented on eod/pollcmds.go
> +	if len(mark) >= 1500 {
embeds don't abide by discord character limit apparently so yeah i'll change that to 2400

2021-07-17 23:43 UTC, Nv7-GitHub approved these changes
Looks good!

2021-07-17 23:44 UTC, merged