Create id.json
Nv7-GitHub/Nv7Haven pull request #73
Opened 2022-01-20 07:45 UTC by IdaeChop

Indonesian Translation V1

2022-01-25 03:40 UTC, Nv7-GitHub commented
Probably pretty out-of-date now, need to update ur fork to match mine

2022-01-25 05:08 UTC, IdaeChop commented
> Probably pretty out-of-date now, need to update ur fork to match mine

I've fetched upstream

2022-01-27 00:03 UTC, Nv7-GitHub commented
Is this up-to-date? (like does it have all the things translation files are supposed to have)

2022-01-27 01:25 UTC, Nv7-GitHub requested changes

2022-01-27 01:25 UTC, Nv7-GitHub commented on eod/translation/languages/id.json
> +{
Can you rename this to `in.json` to match https://www.sitepoint.com/iso-2-letter-language-codes/ ?

2022-01-27 03:48 UTC, Nv7-GitHub commented
There were some more updates, could you add them?

2022-01-27 12:45 UTC, IdaeChop commented on eod/translation/languages/id.json
> +{
I set it as id because the code for Indonesia in ISO-3166 alpha-2 is ID, but I probably should change it yes.

2022-01-27 12:48 UTC, IdaeChop commented
Updated Indonesian Support

2022-01-27 12:49 UTC, IdaeChop commented
> Updated Indonesian Support

It is now done

2022-01-28 02:13 UTC, IdaeChop reviewed
done

2022-01-28 03:20 UTC, Nv7-GitHub requested changes

2022-01-28 03:20 UTC, Nv7-GitHub commented on eod/translation/languages/in.json
> +  "$schema": "../schema.json"
Seems like you're missing `NewComboNews` and `NewElemNews`

2022-01-28 03:30 UTC, IdaeChop commented on eod/translation/languages/in.json
> +  "$schema": "../schema.json"
I see, alright then.

2022-01-28 03:43 UTC, Nv7-GitHub approved these changes
Seems good!

2022-01-28 03:43 UTC, merged