Add a lot of translation support
Nv7-GitHub/Nv7Haven pull request #74
Opened 2022-01-20 17:09 UTC by Sightnado

This adds translation support to a large number of commands.

2022-01-21 03:09 UTC, Nv7-GitHub commented
Holy crap you actually did it

2022-01-21 03:13 UTC, Nv7-GitHub commented on eod/categories/get.go
> +		Title:      fmt.Sprintf(db.config.LangProperty("ElemCategories"), el.Name, len(out)),
Capital C

2022-01-21 03:14 UTC, Nv7-GitHub requested changes
Some compile errors

2022-01-21 03:14 UTC, Nv7-GitHub commented on eod/categories/get.go
> +		Title:      fmt.Sprintf(db.config.LangProperty("ElemCategories"), el.Name, len(out)),
Capital C

2022-01-21 03:14 UTC, Nv7-GitHub commented on eod/categories/get.go
> +		Content: fmt.Sprintf(db.config.langProperty("NameDownloadedCat"), cat.Name),
Capital C

2022-01-21 03:14 UTC, Nv7-GitHub commented on eod/categories/get.go
> +	rsp.Message(db.config.LangProperty("CatSentToDMs"))
Capital C

2022-01-21 03:18 UTC, Nv7-GitHub commented
Wait theres actually a lot more missing Capital C stuff, in VSCode go to Search tab, search for `db.config` and replace with `db.Config`

2022-01-21 03:19 UTC, Sightnado commented
> 

i don't have vscode installed :(

2022-01-21 03:25 UTC, Nv7-GitHub requested changes
Some stuff in the translation file

2022-01-21 03:25 UTC, Nv7-GitHub commented on eod/translation/languages/en.json
> +  "SuggestIdea": "\n 	Suggest it by typing **/suggest**",
Make sure to get rid of tab and replace with `\t`

2022-01-21 03:25 UTC, Nv7-GitHub commented on eod/translation/languages/en.json
> +  "NewAIIdea": "New AI Generated Idea",
Can you split up the text in this chunk based on command with line breaks? Like code for AI would be in a chunk, then there would be a line break, then code for Info would be in a chunk, etc. Like how it is for the stuff I did

2022-01-21 03:25 UTC, Nv7-GitHub commented on eod/translation/schema_config.json
> +  "NewAIIdea": "The message in the New AI Generated Idea button.",
Same for this thing as for `en.json`, please split up chunks

2022-01-21 03:25 UTC, Nv7-GitHub requested changes
Some stuff in the translation file

2022-01-21 03:36 UTC, Nv7-GitHub requested changes
Few bugs, seems pretty good!

2022-01-21 03:36 UTC, Nv7-GitHub commented on eod/translation/schema_config.json
> +  "SuggestedElem": "Tells the user what combo they just suggested.",
Can't have , in last one! (just get rid of comma in this line)

2022-01-21 03:36 UTC, Nv7-GitHub commented on eod/categories/get.go
> +		Content: fmt.Sprintf(db.Config.langProperty("NameDownloadedCat"), cat.Name),
Capital L!

2022-01-21 03:36 UTC, Nv7-GitHub requested changes

2022-01-21 03:36 UTC, Nv7-GitHub commented on eod/translation/schema.json
> +    },
Oh also this needs no comma

2022-01-25 00:24 UTC, Sightnado commented
also added an English (UK) translation file for no reason in particular other than to test to see if changing languages actually works

2022-01-25 03:31 UTC, Nv7-GitHub approved these changes
Seems good!

2022-01-25 03:32 UTC, merged