Filipino Translation Support
Nv7-GitHub/Nv7Haven pull request #77
Opened 2022-01-25 05:01 UTC by Riskitizen

i forgor to add the last 2 lines at the first commit lmao

2022-01-25 05:06 UTC, IdaeChop commented
cool

2022-01-27 00:03 UTC, Nv7-GitHub commented
Is it up to date?

2022-01-27 01:05 UTC, Riskitizen commented
yeah

2022-01-27 01:09 UTC, Nv7-GitHub reviewed
Missing some things, seems good otherwise

2022-01-27 01:09 UTC, Nv7-GitHub commented on eod/translation/languages/fil.json
> +  "CannotHaveBothElemAndID": "Hindi mo maaaring ilagay nang magkasabay ang element at element ID ng isang element!",
Missing `AllCats` and `Uncategorized`

2022-01-27 01:10 UTC, Riskitizen commented on eod/translation/languages/fil.json
> +  "CannotHaveBothElemAndID": "Hindi mo maaaring ilagay nang magkasabay ang element at element ID ng isang element!",
oh alr

2022-01-27 01:13 UTC, Nv7-GitHub commented on eod/translation/languages/fil.json
> +  "CannotHaveBothElemAndID": "Hindi mo maaaring ilagay nang magkasabay ang element at element ID ng isang element!",
Wait bug in scheme

2022-01-27 01:14 UTC, Nv7-GitHub commented
Can you get latest updates to get updated schema

2022-01-27 01:16 UTC, Riskitizen commented
fetched upstream

2022-01-27 01:19 UTC, Nv7-GitHub requested changes
I think you are missing a few things

2022-01-27 01:19 UTC, Nv7-GitHub commented on eod/translation/languages/fil.json
> +
Missing `CalculatingPing`, `NewComboNews`, `NewElemNews`

2022-01-27 01:27 UTC, Nv7-GitHub commented on eod/translation/languages/fil.json
> +
Also, can you rename to `tl.json` in order to fit ISO 2-letter language codes?

2022-01-27 01:31 UTC, Riskitizen commented on eod/translation/languages/fil.json
> +
ok sure

2022-01-27 03:48 UTC, Nv7-GitHub commented
There were some more updates, could you add them?

2022-01-27 04:40 UTC, Riskitizen commented
Supposed to be Added stuff from lines 198 to 200 + improved some translations

2022-01-27 04:47 UTC, Nv7-GitHub approved these changes
Seems good!

2022-01-27 04:47 UTC, merged