Add OwO version of English
Nv7-GitHub/Nv7Haven pull request #83
Opened 2022-01-27 15:54 UTC by Lily-129

:eggTF:

2022-01-28 03:18 UTC, Nv7-GitHub requested changes

2022-01-28 03:18 UTC, Nv7-GitHub commented on eod/translation/languages/en_owo.json
> +  "Name": "Engwish (US)",
Can you make it `Engwish (Owo)`?

2022-01-28 12:31 UTC, Lily-129 commented on eod/translation/languages/en_owo.json
> +  "Name": "Engwish (US)",
I made the change. Do I have to recreate the pull request for it to apply?

2022-01-30 20:25 UTC, rayzchen commented on eod/translation/languages/en_owo.json
> +  "Name": "Engwish (US)",
no

2022-01-30 22:53 UTC, Nv7-GitHub approved these changes
Seems good!

2022-01-30 22:53 UTC, merged