Chinese translation file
Nv7-GitHub/Nv7Haven pull request #91
Opened 2022-01-30 20:03 UTC by rayzchen

2022-01-30 23:05 UTC, Nv7-GitHub requested changes
Seems good! (Just extra space)

2022-01-30 23:05 UTC, Nv7-GitHub commented on eod/translation/languages/zh.json
> +  "Name": "Chinese（Simplified）",
Extra space

2022-01-31 10:41 UTC, rayzchen commented
Done

2022-02-01 04:16 UTC, Nv7-GitHub approved these changes
Seems good!

2022-02-01 04:16 UTC, merged